# Generated by Django 5.0 on 2024-01-15 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_goals_experience_user_goals_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_goals',
            name='weekly_target',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
