# Generated by Django 5.0 on 2024-01-08 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_food_owner_food_day_food_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='fat_g',
            new_name='fat',
        ),
        migrations.AlterField(
            model_name='macro_day',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 8), unique=True),
        ),
    ]
