# Generated by Django 5.0 on 2024-01-08 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_fat_g_food_fat_alter_macro_day_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='owner',
        ),
        migrations.AlterField(
            model_name='weight',
            name='entry_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.macro_day', unique=True),
        ),
    ]
